#include "infrastructure/basic_manifest.hpp"

basic_manifest::basic_manifest(
    db& database,
    initial_goal_exprs& initial_goals,
    uint32_t initial_frame_offset,
    size_t max_resolutions,
    uint32_t random_seed)
    : database_(database),
      initial_goals_(initial_goals),
      max_resolutions_(max_resolutions),
      globalizer_(globalizer_obj_),
      trail_(trail_obj_),
      bind_map_(bind_map_obj_),
      bind_map_factory_(bind_map_factory_obj_),
      unifier_factory_(unifier_factory_obj_),
      expr_pool_(expr_pool_obj_),
      frame_allocator_(frame_allocator_obj_),
      lineage_pool_(lineage_pool_obj_),
      ra_active_goals_(ra_active_goals_obj_),
      goal_exprs_(goal_exprs_obj_),
      goal_candidate_rules_(goal_candidate_rules_obj_),
      unit_goals_(unit_goals_obj_),
      decision_memory_(decision_memory_obj_),
      resolution_memory_(resolution_memory_obj_),
      elimination_backlog_(elimination_backlog_obj_),
      cdcl_(cdcl_obj_),
      mhu_(mhu_obj_),
      joint_(joint_obj_),
      candidate_frame_offsets_(candidate_frame_offsets_obj_),
      get_resolution_rule_(get_resolution_rule_obj_),
      conflict_detector_(conflict_detector_obj_),
      unit_goal_detector_(unit_goal_detector_obj_),
      solution_detector_(solution_detector_obj_),
      goal_activator_(goal_activator_obj_),
      goal_deactivator_(goal_deactivator_obj_),
      candidate_activator_(candidate_activator_obj_),
      candidate_deactivator_(candidate_deactivator_obj_),
      elimination_router_(elimination_router_obj_),
      get_unit_resolution_(get_unit_resolution_obj_),
      make_initial_goal_lineage_(make_initial_goal_lineage_obj_),
      initial_goal_activator_(initial_goal_activator_obj_),
      rng_(rng_obj_),
      random_decision_generator_(random_decision_generator_obj_),
      resolver_(resolver_obj_),
      set_up_sim_(set_up_sim_obj_),
      tear_down_sim_(tear_down_obj_),
      run_sim_(run_sim_obj_),
      solver_(solver_obj_),
      // --- private value member initialization ---
      globalizer_obj_(),
      trail_obj_(),
      bind_map_obj_(globalizer_obj_),
      bind_map_factory_obj_(globalizer_obj_),
      unifier_factory_obj_(globalizer_obj_),
      lineage_pool_obj_(),
      rule_id_set_factory_obj_(),
      ra_rule_id_set_factory_obj_(),
      ra_active_goals_obj_(),
      goal_exprs_obj_(),
      goal_candidate_rules_obj_(ra_rule_id_set_factory_obj_),
      unit_goals_obj_(),
      decision_memory_obj_(),
      resolution_memory_obj_(),
      candidate_frame_offsets_obj_(),
      chosen_goal_candidates_obj_(),
      expr_pool_obj_(),
      frame_allocator_obj_(initial_frame_offset),
      elimination_backlog_obj_(trail_obj_),
      cdcl_obj_(chosen_goal_candidates_obj_),
      mhu_obj_(bind_map_obj_, lineage_pool_obj_, expr_pool_obj_,
               bind_map_factory_obj_, unifier_factory_obj_, goal_candidate_rules_obj_),
      joint_obj_(cdcl_obj_, mhu_obj_),
      get_resolution_rule_obj_(database),
      conflict_detector_obj_(goal_candidate_rules_obj_),
      unit_goal_detector_obj_(goal_candidate_rules_obj_),
      solution_detector_obj_(ra_active_goals_obj_),
      goal_activator_obj_(goal_exprs_obj_, goal_candidate_rules_obj_, ra_active_goals_obj_,
                          candidate_frame_offsets_obj_, get_resolution_rule_obj_),
      goal_deactivator_obj_(goal_exprs_obj_, goal_candidate_rules_obj_, ra_active_goals_obj_),
      candidate_activator_obj_(frame_allocator_obj_, candidate_frame_offsets_obj_, mhu_obj_,
                               elimination_backlog_obj_, goal_exprs_obj_, database,
                               goal_candidate_rules_obj_),
      candidate_deactivator_obj_(candidate_frame_offsets_obj_, goal_candidate_rules_obj_),
      elimination_router_obj_(goal_candidate_rules_obj_, ra_active_goals_obj_,
                              elimination_backlog_obj_, candidate_deactivator_obj_),
      get_unit_resolution_obj_(goal_candidate_rules_obj_, lineage_pool_obj_),
      make_initial_goal_lineage_obj_(lineage_pool_obj_),
      initial_goal_activator_obj_(initial_goals, make_initial_goal_lineage_obj_,
                                  goal_exprs_obj_, goal_candidate_rules_obj_, ra_active_goals_obj_),
      goal_candidates_deactivator_obj_(goal_candidate_rules_obj_, lineage_pool_obj_,
                                       candidate_deactivator_obj_),
      goal_candidates_activator_obj_(database, lineage_pool_obj_, candidate_activator_obj_,
                                     conflict_detector_obj_, unit_goal_detector_obj_, unit_goals_obj_),
      subgoals_activator_obj_(lineage_pool_obj_, goal_activator_obj_, database,
                              goal_candidates_activator_obj_),
      initial_goals_activator_obj_(initial_goals, initial_goal_activator_obj_,
                                   make_initial_goal_lineage_obj_, goal_candidates_activator_obj_),
      rng_obj_(random_seed),
      random_decision_generator_obj_(lineage_pool_obj_, ra_active_goals_obj_,
                                     goal_candidate_rules_obj_, rng_obj_),
      resolver_obj_(goal_deactivator_obj_, subgoals_activator_obj_,
                    goal_candidates_deactivator_obj_, chosen_goal_candidates_obj_),
      set_up_sim_obj_(trail_obj_),
      tear_down_obj_(trail_obj_, unit_goals_obj_, decision_memory_obj_, resolution_memory_obj_,
                     goal_candidate_rules_obj_, goal_exprs_obj_, ra_active_goals_obj_,
                     candidate_frame_offsets_obj_, mhu_obj_, bind_map_obj_,
                     lineage_pool_obj_, frame_allocator_obj_, cdcl_obj_,
                     chosen_goal_candidates_obj_),
      run_sim_obj_(initial_goals_activator_obj_, solution_detector_obj_, conflict_detector_obj_,
                   unit_goal_detector_obj_, unit_goals_obj_, unit_goals_obj_,
                   random_decision_generator_obj_, joint_obj_, elimination_router_obj_,
                   resolver_obj_, get_unit_resolution_obj_, decision_memory_obj_,
                   resolution_memory_obj_, max_resolutions),
      solver_obj_(set_up_sim_obj_, tear_down_obj_, run_sim_obj_,
                  decision_memory_obj_, decision_memory_obj_,
                  lineage_pool_obj_, cdcl_obj_, elimination_router_obj_) {}
