#include "infrastructure/basic_manifest.hpp"

basic_manifest::basic_manifest(
    db& database,
    initial_goal_exprs& initial_goals,
    uint32_t initial_frame_offset,
    size_t max_resolutions,
    uint32_t random_seed)
    : globalizer_(),
      bind_map_(globalizer_),
      bind_map_factory_(globalizer_),
      unifier_factory_(globalizer_),
      lineage_pool_(),
      rule_id_set_factory_(),
      ra_rule_id_set_factory_(),
      ra_active_goals_(),
      goal_exprs_(),
      querier_(goal_exprs_, database, database),
      goal_candidate_rules_(ra_rule_id_set_factory_),
      unit_goals_(),
      decision_memory_(),
      resolution_memory_(),
      candidate_frame_offsets_(),
      chosen_goal_candidates_(),
      expr_pool_(),
      frame_allocator_(initial_frame_offset),
      elimination_backlog_(),
      cdcl_(chosen_goal_candidates_),
      mhu_(bind_map_, bind_map_, lineage_pool_, expr_pool_,
           bind_map_factory_, unifier_factory_, goal_candidate_rules_),
      joint_(cdcl_, mhu_),
      get_resolution_rule_(database),
      conflict_detector_(goal_candidate_rules_),
      unit_goal_detector_(goal_candidate_rules_),
      solution_detector_(ra_active_goals_),
      goal_activator_(goal_exprs_, goal_candidate_rules_, ra_active_goals_,
                      candidate_frame_offsets_, get_resolution_rule_),
      goal_deactivator_(goal_exprs_, goal_candidate_rules_, ra_active_goals_),
      candidate_activator_(frame_allocator_, candidate_frame_offsets_, mhu_,
                           elimination_backlog_, goal_exprs_, database,
                           goal_candidate_rules_),
      candidate_deactivator_(candidate_frame_offsets_, goal_candidate_rules_),
      elimination_router_(goal_candidate_rules_, ra_active_goals_,
                          elimination_backlog_, candidate_deactivator_),
      get_unit_resolution_(goal_candidate_rules_, lineage_pool_),
      make_initial_goal_lineage_(lineage_pool_),
      initial_goal_activator_(initial_goals, make_initial_goal_lineage_,
                              goal_exprs_, goal_candidate_rules_, ra_active_goals_),
      goal_candidates_deactivator_(goal_candidate_rules_, lineage_pool_,
                                   candidate_deactivator_),
      goal_candidates_activator_(querier_, lineage_pool_, candidate_activator_,
                                 conflict_detector_, unit_goal_detector_, unit_goals_),
      subgoals_activator_(lineage_pool_, goal_activator_, database,
                          goal_candidates_activator_),
      initial_goals_activator_(initial_goals, initial_goal_activator_,
                               make_initial_goal_lineage_, goal_candidates_activator_),
      rng_(random_seed),
      random_decision_generator_(lineage_pool_, ra_active_goals_,
                                 goal_candidate_rules_, rng_),
      resolver_(goal_deactivator_, subgoals_activator_,
                goal_candidates_deactivator_, chosen_goal_candidates_),
      set_up_sim_(elimination_backlog_),
      tear_down_sim_(elimination_backlog_, unit_goals_, decision_memory_, resolution_memory_,
                     goal_candidate_rules_, goal_exprs_, ra_active_goals_,
                     candidate_frame_offsets_, mhu_, bind_map_,
                     lineage_pool_, frame_allocator_, cdcl_,
                     chosen_goal_candidates_),
      resolution_recorder_(decision_memory_, resolution_memory_),
      run_sim_(initial_goals_activator_, solution_detector_, conflict_detector_,
               unit_goal_detector_, unit_goals_, unit_goals_,
               random_decision_generator_, joint_, elimination_router_,
               resolver_, get_unit_resolution_, resolution_recorder_,
               resolution_recorder_, resolution_memory_, max_resolutions),
      solver_(set_up_sim_, tear_down_sim_, run_sim_,
              decision_memory_, decision_memory_,
              lineage_pool_, cdcl_, elimination_router_),
      normalizer_(globalizer_, expr_pool_, expr_pool_, bind_map_),
      driver_(solver_.solve()) {}
