#include "infrastructure/dbuct_ridge_manifest.hpp"

dbuct_ridge_manifest::dbuct_ridge_manifest(
    db& database,
    initial_goal_exprs& initial_goals,
    uint32_t initial_frame_offset,
    size_t max_resolutions,
    uint32_t random_seed,
    double exploration_constant,
    size_t grant_increment_interval)
    : globalizer_(),
      frame_depth_(),
      bind_map_(globalizer_),
      bind_map_factory_(globalizer_),
      unifier_factory_(globalizer_),
      lineage_pool_(),
      ra_rule_id_set_factory_(),
      srt_active_goals_(),
      goal_exprs_(),
      goal_candidate_rules_(ra_rule_id_set_factory_),
      unit_goals_(),
      decision_memory_(),
      resolution_memory_(),
      candidate_frame_offsets_(),
      chosen_goal_candidates_(),
      expr_pool_(),
      frame_allocator_(initial_frame_offset),
      elimination_backlog_(),
      nearest_decision_(),
      avoidance_unit_boundary_(nearest_decision_, frame_depth_),
      cdcl_(chosen_goal_candidates_, avoidance_unit_boundary_, decision_memory_,
            avoidance_unit_boundary_, avoidance_unit_boundary_),
      mhu_(bind_map_, lineage_pool_, expr_pool_,
           bind_map_factory_, unifier_factory_, goal_candidate_rules_),
      hub_(frame_depth_, goal_exprs_, goal_candidate_rules_, chosen_goal_candidates_,
           decision_memory_, resolution_memory_, unit_goals_, candidate_frame_offsets_,
           frame_allocator_, nearest_decision_, elimination_backlog_,
           avoidance_unit_boundary_, srt_active_goals_, bind_map_, mhu_, cdcl_),
      dbuct_joint_(cdcl_, mhu_),
      resolution_recorder_(decision_memory_, resolution_memory_, nearest_decision_,
                         avoidance_unit_boundary_),
      get_resolution_rule_(database),
      conflict_detector_(goal_candidate_rules_),
      unit_goal_detector_(goal_candidate_rules_),
      solution_detector_(srt_active_goals_),
      goal_activator_(goal_exprs_, goal_candidate_rules_, srt_active_goals_,
                      candidate_frame_offsets_, get_resolution_rule_),
      srt_goal_deactivator_(goal_exprs_, goal_candidate_rules_),
      candidate_activator_(frame_allocator_, candidate_frame_offsets_, mhu_,
                           elimination_backlog_, goal_exprs_, database,
                           goal_candidate_rules_),
      candidate_deactivator_(candidate_frame_offsets_, goal_candidate_rules_),
      elimination_router_(goal_candidate_rules_, srt_active_goals_,
                          elimination_backlog_, candidate_deactivator_),
      get_unit_resolution_(goal_candidate_rules_, lineage_pool_),
      make_initial_goal_lineage_(lineage_pool_),
      initial_goal_activator_(initial_goals, make_initial_goal_lineage_,
                              goal_exprs_, goal_candidate_rules_, srt_active_goals_),
      goal_candidates_deactivator_(goal_candidate_rules_, lineage_pool_,
                                   candidate_deactivator_),
      goal_candidates_activator_(database, lineage_pool_, candidate_activator_,
                                 conflict_detector_, unit_goal_detector_, unit_goals_),
      subgoals_activator_(lineage_pool_, goal_activator_, database,
                          goal_candidates_activator_),
      srt_subgoals_activator_(srt_active_goals_, subgoals_activator_),
      initial_goals_activator_(initial_goals, initial_goal_activator_,
                               make_initial_goal_lineage_, goal_candidates_activator_),
      srt_initial_goals_activator_(srt_active_goals_, initial_goals_activator_),
      resolver_(srt_goal_deactivator_, srt_subgoals_activator_,
                goal_candidates_deactivator_, chosen_goal_candidates_),
      ridge_reward_(decision_memory_),
      rng_(random_seed),
      dbuct_tree_walker_(),
      dbuct_visits_table_(),
      dbuct_value_table_(),
      dbuct_dispatches_table_(),
      dbuct_batch_(grant_increment_interval),
      dbuct_rollout_(rng_),
      dbuct_(dbuct_visits_table_, dbuct_value_table_,
             dbuct_visits_table_, dbuct_value_table_,
             dbuct_dispatches_table_, dbuct_dispatches_table_,
             dbuct_batch_, dbuct_tree_walker_, dbuct_rollout_,
             0, exploration_constant),
      dbuct_sim_(hub_, avoidance_unit_boundary_, dbuct_),
      mcts_decision_generator_(lineage_pool_, srt_active_goals_,
                               dbuct_sim_, goal_candidate_rules_),
      frontier_ready_(),
      run_sim_(frontier_ready_, solution_detector_, conflict_detector_,
               unit_goal_detector_, unit_goals_, unit_goals_,
               mcts_decision_generator_, dbuct_joint_, elimination_router_,
               resolver_, get_unit_resolution_, resolution_recorder_,
               resolution_recorder_, resolution_memory_, max_resolutions),
      solver_(srt_initial_goals_activator_, run_sim_, decision_memory_,
              ridge_reward_, dbuct_sim_, dbuct_sim_, cdcl_, mhu_, elimination_router_,
              conflict_detector_, unit_goal_detector_, unit_goals_) {
}
