#include "infrastructure/horizon_manifest.hpp"

namespace {

constexpr double k_total_weight = 1.0;

double compute_initial_goal_weight(size_t count) {
    if (count == 0)
        return 0.0;
    return k_total_weight / static_cast<double>(count);
}

}

horizon_manifest::horizon_manifest(
    db& database,
    initial_goal_exprs& initial_goals,
    uint32_t initial_frame_offset,
    size_t max_resolutions,
    uint32_t random_seed,
    double exploration_constant)
    : globalizer_(),
      bind_map_(globalizer_),
      bind_map_factory_(globalizer_),
      unifier_factory_(globalizer_),
      lineage_pool_(),
      rule_id_set_factory_(),
      ra_rule_id_set_factory_(),
      srt_active_goals_(),
      goal_exprs_(),
      querier_(goal_exprs_, database, database),
      goal_weights_(),
      cumulative_grounded_weight_(),
      initial_goal_weight_(compute_initial_goal_weight(initial_goals.count())),
      goal_candidate_rules_(ra_rule_id_set_factory_),
      unit_goals_(),
      decision_memory_(),
      resolution_memory_(),
      candidate_frame_offsets_(),
      chosen_goal_candidates_(),
      expr_pool_(),
      frame_allocator_(initial_frame_offset),
      elimination_backlog_(),
      cdcl_(chosen_goal_candidates_),
      mhu_(bind_map_, bind_map_, lineage_pool_, expr_pool_,
           bind_map_factory_, unifier_factory_, goal_candidate_rules_),
      joint_(cdcl_, mhu_),
      get_resolution_rule_(database),
      conflict_detector_(goal_candidate_rules_),
      unit_goal_detector_(goal_candidate_rules_),
      solution_detector_(srt_active_goals_),
      goal_activator_(goal_exprs_, goal_candidate_rules_, srt_active_goals_,
                      candidate_frame_offsets_, get_resolution_rule_),
      horizon_goal_activator_(goal_activator_, goal_weights_, goal_weights_, database),
      srt_goal_deactivator_(goal_exprs_, goal_candidate_rules_),
      horizon_goal_deactivator_(srt_goal_deactivator_, goal_weights_),
      candidate_activator_(frame_allocator_, candidate_frame_offsets_, mhu_,
                           elimination_backlog_, goal_exprs_, database,
                           goal_candidate_rules_),
      candidate_deactivator_(candidate_frame_offsets_, goal_candidate_rules_),
      elimination_router_(goal_candidate_rules_, srt_active_goals_,
                          elimination_backlog_, candidate_deactivator_),
      get_unit_resolution_(goal_candidate_rules_, lineage_pool_),
      make_initial_goal_lineage_(lineage_pool_),
      initial_goal_activator_(initial_goals, make_initial_goal_lineage_,
                              goal_exprs_, goal_candidate_rules_, srt_active_goals_),
      horizon_initial_goal_activator_(initial_goal_activator_, make_initial_goal_lineage_,
                                      goal_weights_, initial_goal_weight_),
      goal_candidates_deactivator_(goal_candidate_rules_, lineage_pool_,
                                   candidate_deactivator_),
      goal_candidates_activator_(querier_, lineage_pool_,
                                 candidate_activator_, conflict_detector_, unit_goal_detector_,
                                 unit_goals_),
      subgoals_activator_(lineage_pool_, horizon_goal_activator_, database,
                          goal_candidates_activator_),
      srt_subgoals_activator_(srt_active_goals_, srt_active_goals_, subgoals_activator_),
      initial_goals_activator_(initial_goals, horizon_initial_goal_activator_,
                               make_initial_goal_lineage_, goal_candidates_activator_),
      srt_initial_goals_activator_(srt_active_goals_, initial_goals_activator_),
      resolver_(horizon_goal_deactivator_, srt_subgoals_activator_,
                goal_candidates_deactivator_, chosen_goal_candidates_),
      horizon_resolver_(resolver_, database, goal_weights_,
                        cumulative_grounded_weight_),
      set_up_sim_(elimination_backlog_),
      tear_down_sim_(elimination_backlog_, unit_goals_, decision_memory_, resolution_memory_,
                     goal_candidate_rules_, goal_exprs_, srt_active_goals_,
                     candidate_frame_offsets_, mhu_, bind_map_,
                     lineage_pool_, frame_allocator_, cdcl_,
                     chosen_goal_candidates_),
      horizon_reward_(cumulative_grounded_weight_),
      value_delta_(),
      rng_(random_seed),
      mcts_sim_(value_delta_, lineage_pool_, rng_, exploration_constant),
      horizon_set_up_sim_(mcts_sim_, set_up_sim_),
      horizon_tear_down_sim_(horizon_reward_, value_delta_, mcts_sim_,
                             goal_weights_, cumulative_grounded_weight_, tear_down_sim_),
      mcts_decision_generator_(lineage_pool_, srt_active_goals_, srt_active_goals_,
                               srt_active_goals_, mcts_sim_, goal_candidate_rules_),
      resolution_recorder_(decision_memory_, resolution_memory_),
      run_sim_(srt_initial_goals_activator_, solution_detector_,
               conflict_detector_, unit_goal_detector_,
               unit_goals_, unit_goals_,
               mcts_decision_generator_, joint_, elimination_router_,
               horizon_resolver_, get_unit_resolution_, resolution_recorder_,
               resolution_recorder_, resolution_memory_, max_resolutions),
      solver_(horizon_set_up_sim_, horizon_tear_down_sim_, run_sim_,
              decision_memory_, decision_memory_,
              lineage_pool_, cdcl_, elimination_router_),
      normalizer_(globalizer_, expr_pool_, expr_pool_, bind_map_),
      driver_(solver_.solve()) {}
