#include "infrastructure/quell_fc_manifest.hpp"

quell_fc_manifest::quell_fc_manifest(
    db& database,
    initial_goal_exprs& initial_goals,
    uint32_t initial_frame_offset,
    size_t max_resolutions,
    uint32_t random_seed,
    double exploration_constant,
    double work_decay_k,
    double work_decay_j)
    : globalizer_(),
      bind_map_(globalizer_),
      bind_map_factory_(globalizer_),
      local_bind_map_pool_(),
      unifier_factory_(globalizer_),
      lineage_pool_(),
      rule_id_set_factory_(),
      ra_rule_id_set_factory_(),
      srt_active_goals_(),
      goal_exprs_(),
      querier_(goal_exprs_, database, database),
      goal_depths_(),
      goal_work_values_(),
      remaining_work_(),
      goal_work_function_(work_decay_k, work_decay_j),
      goal_candidate_rules_(ra_rule_id_set_factory_),
      rp_compute_fewer_candidate_goal_value_(goal_candidate_rules_),
      rp_srt_active_goals_(srt_active_goals_, srt_active_goals_,
                           srt_active_goals_, srt_active_goals_,
                           srt_active_goals_),
      unit_goals_(),
      decision_memory_(),
      resolution_memory_(),
      candidate_frame_offsets_(),
      chosen_goal_candidates_(),
      expr_pool_(),
      frame_allocator_(initial_frame_offset),
      elimination_backlog_(),
      cdcl_(chosen_goal_candidates_),
      mhu_(bind_map_, bind_map_, lineage_pool_, expr_pool_,
           local_bind_map_pool_, local_bind_map_pool_, local_bind_map_pool_,
           bind_map_factory_, unifier_factory_, goal_candidate_rules_),
      joint_(cdcl_, mhu_),
      get_resolution_rule_(database),
      conflict_detector_(goal_candidate_rules_),
      unit_goal_detector_(goal_candidate_rules_),
      solution_detector_(srt_active_goals_),
      goal_activator_(goal_exprs_, goal_candidate_rules_, rp_srt_active_goals_,
                      candidate_frame_offsets_, get_resolution_rule_),
      quell_goal_activator_(goal_activator_, goal_depths_, goal_depths_, goal_work_values_, goal_work_function_,
                            remaining_work_),
      srt_goal_deactivator_(goal_exprs_, goal_candidate_rules_),
      quell_goal_deactivator_(srt_goal_deactivator_, goal_depths_, goal_work_values_),
      candidate_activator_(frame_allocator_, candidate_frame_offsets_, mhu_,
                           elimination_backlog_, goal_exprs_, database,
                           goal_candidate_rules_),
      candidate_deactivator_(candidate_frame_offsets_, goal_candidate_rules_),
      elimination_router_(goal_candidate_rules_, srt_active_goals_,
                          elimination_backlog_, candidate_deactivator_),
      rp_fewer_candidates_elimination_router_(
          elimination_router_, rp_compute_fewer_candidate_goal_value_,
          rp_srt_active_goals_),
      get_unit_resolution_(goal_candidate_rules_, lineage_pool_),
      make_initial_goal_lineage_(lineage_pool_),
      initial_goal_activator_(initial_goals, make_initial_goal_lineage_,
                              goal_exprs_, goal_candidate_rules_, rp_srt_active_goals_),
      quell_initial_goal_activator_(initial_goal_activator_, make_initial_goal_lineage_,
                                    goal_depths_, goal_work_values_, goal_work_function_, remaining_work_),
      goal_candidates_deactivator_(goal_candidate_rules_, lineage_pool_,
                                   candidate_deactivator_),
      goal_candidates_activator_(querier_, lineage_pool_,
                                 candidate_activator_, conflict_detector_, unit_goal_detector_,
                                 unit_goals_),
      rp_fewer_candidate_goal_candidates_activator_(
          goal_candidates_activator_, rp_compute_fewer_candidate_goal_value_,
          rp_srt_active_goals_),
      subgoals_activator_(lineage_pool_, quell_goal_activator_, database,
                          goal_candidates_activator_),
      srt_subgoals_activator_(rp_srt_active_goals_, srt_active_goals_, subgoals_activator_),
      rp_fewer_candidate_srt_subgoals_activator_(
          srt_subgoals_activator_, database, lineage_pool_,
          rp_compute_fewer_candidate_goal_value_, rp_srt_active_goals_),
      initial_goals_activator_(initial_goals, quell_initial_goal_activator_,
                               make_initial_goal_lineage_, rp_fewer_candidate_goal_candidates_activator_),
      srt_initial_goals_activator_(srt_active_goals_, initial_goals_activator_),
      resolver_(quell_goal_deactivator_, rp_fewer_candidate_srt_subgoals_activator_,
                goal_candidates_deactivator_, chosen_goal_candidates_),
      quell_resolver_(resolver_, goal_work_values_, remaining_work_),
      set_up_sim_(elimination_backlog_),
      tear_down_sim_(elimination_backlog_, unit_goals_, decision_memory_, resolution_memory_,
                     goal_candidate_rules_, goal_exprs_, rp_srt_active_goals_,
                     candidate_frame_offsets_, mhu_, bind_map_,
                     lineage_pool_, frame_allocator_, cdcl_,
                     chosen_goal_candidates_),
      quell_reward_(remaining_work_),
      value_delta_(),
      rng_(random_seed),
      mcts_visits_table_(),
      mcts_value_table_(),
      tree_walker_(),
      goal_rollout_(rp_srt_active_goals_),
      rule_rollout_(rng_),
      mcts_rollout_(goal_rollout_, rule_rollout_),
      mcts_root_tree_node_(),
      exploration_constant_(exploration_constant),
      mcts_sim_(mcts_visits_table_, mcts_visits_table_,
                mcts_value_table_, mcts_value_table_,
                tree_walker_, mcts_rollout_, value_delta_,
                exploration_constant_, mcts_root_tree_node_),
      quell_set_up_sim_(mcts_sim_, set_up_sim_),
      quell_tear_down_sim_(quell_reward_, value_delta_, mcts_sim_,
                           goal_depths_, goal_work_values_, remaining_work_, tear_down_sim_),
      mcts_decision_generator_(lineage_pool_, srt_active_goals_, srt_active_goals_,
                               srt_active_goals_, mcts_sim_, goal_candidate_rules_),
      resolution_recorder_(decision_memory_, resolution_memory_),
      run_sim_(srt_initial_goals_activator_, solution_detector_,
               conflict_detector_, unit_goal_detector_,
               unit_goals_, unit_goals_,
               mcts_decision_generator_, joint_, rp_fewer_candidates_elimination_router_,
               quell_resolver_, get_unit_resolution_, resolution_recorder_,
               resolution_recorder_, resolution_memory_, max_resolutions),
      solver_(quell_set_up_sim_, quell_tear_down_sim_, run_sim_,
              decision_memory_, decision_memory_,
              lineage_pool_, cdcl_, rp_fewer_candidates_elimination_router_),
      normalizer_(globalizer_, expr_pool_, expr_pool_, bind_map_),
      driver_(solver_.solve()) {}
